name: GammaLabAnalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - nodejs
  - python=3.6.5
  - ipympl
  - ipykernel
  - jupyter
  - jupyterlab
  - matplotlib
  - cython
  - numpy
  - scipy
  - pandas
  - nbconvert
  - nbstripout
